#!/usr/bin/env bash

echo "
----------------------
  Deploying front end to AWS
----------------------
"
AWS="ubuntu@ec2-54-219-54-236.us-west-1.compute.amazonaws.com"
BASEDIR=$(dirname "$0")

ssh -i ~/workspace/reader-aws-key.pem \
"$AWS" \
'rm -rf /opt/frontend/*'

cd "$BASEDIR" && cd ../frontend
npm run build
scp -i ~/workspace/reader-aws-key.pem \
-r ~/workspace/reader/frontend/dist/* \
"$AWS":/opt/frontend
