#!/usr/bin/env bash
echo "
----------------------
  vvvvvvvvvvvvvvvv
  Deploying BACK END to AWS
  ^^^^^^^^^^^^^^^^
----------------------
"

echo "
----------------------
  Removing previous files
----------------------
"
AWS="ubuntu@ec2-54-219-54-236.us-west-1.compute.amazonaws.com"
BASEDIR=$(dirname "$0")
echo "$BASEDIR"
ssh -i ~/workspace/reader-aws-key.pem \
"$AWS" \
'rm -rf /opt/backend/*'

echo "
----------------------
  Transferring new files
----------------------
"
cd "$BASEDIR" && cd ..
scp -i ~/workspace/reader-aws-key.pem \
-r ~/workspace/reader/index.js \
"$AWS":/opt/backend
scp -i ~/workspace/reader-aws-key.pem \
-r ~/workspace/reader/models \
"$AWS":/opt/backend
scp -i ~/workspace/reader-aws-key.pem \
-r ~/workspace/reader/package.json \
"$AWS":/opt/backend
scp -i ~/workspace/reader-aws-key.pem \
-r ~/workspace/reader/public \
"$AWS":/opt/backend
scp -i ~/workspace/reader-aws-key.pem \
-r ~/workspace/reader/routes \
"$AWS":/opt/backend
scp -i ~/workspace/reader-aws-key.pem \
-r ~/workspace/reader/scripts/ \
"$AWS":/opt/backend


echo "
----------------------
  Installing node
----------------------
"
ssh -i ~/workspace/reader-aws-key.pem \
"$AWS" \
'cd /opt/backend && npm install'

echo "
----------------------
  Clearing and Seeding database
----------------------
"
ssh -i ~/workspace/reader-aws-key.pem \
"$AWS" \
"cd /opt/backend && mongo /opt/backend/scripts/truncate_db.js"
ssh -i ~/workspace/reader-aws-key.pem \
"$AWS" \
"cd /opt/backend && mongo /opt/backend/scripts/seed_db.js"

echo "
----------------------
  Restarting node server
----------------------
"
ssh -i ~/workspace/reader-aws-key.pem \
"$AWS" \
'cd /opt/backend; sudo pm2 delete "all"; sudo pm2 start index.js'
